[profile.default]
src = "src"
out = "out"
solc = "0.8.23"
libs = ["lib"]
allow_paths = ["../../node_modules"]
fs_permissions = [{ access = "read", path = "./test/utils/etc/palettes.json"},]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[fmt]

quote_style = "single"
line_length = 80
single_line_statement_blocks = "multi"