name: Build Containers
on:
  push:
    branches:
      - main
permissions:
  actions: read
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Reclaim the bytes
        uses: data-intuitive/reclaim-the-bytes@v2
        with:
          remove-hosted-tool-cache: true
          remove-go: true
          remove-codeql: true
          remove-powershell: true
          remove-android-sdk: true
          remove-haskell-ghc: true
          remove-swift: true
          remove-dotnet: true
          remove-docker-images: true
          remove-swap: false
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        id: setSHAs
        uses: nrwl/nx-set-shas@v4
        with:
          main-branch-name: ${{ github.ref_name }}
      - run: echo "Building containers"
      - run: npm install --include=dev --legacy-peer-deps
      - name: Set Container Tag
        id: vars
        run: echo "container_tag=sha-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Build
        id: build
        run: INPUT_GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} npx nx affected -t deploy --base=${{ steps.setSHAs.outputs.base }} --head=${{ steps.setSHAs.outputs.head }} --verbose
